site_name: Submerged program
theme:
  theme:
  name: readthedocs
  highlightjs: true
  prev_next_buttons_location: top
  logo: ./logo.png
  hljs_languages:
    - yaml
    - rust
  

plugins:
  - search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.escapeall:
        hardbreak: true



